version: '3.9'
services:
  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: hym_lab
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''